### ISSUE TITLE
Error on empty nodes in rules

### ISSUE THREAD

**Issue by ai** [ben-eb/postcss-merge-rules#2]
CSS input:

https://github.com/tsergeytovarov/vkino-dev/blob/master/src/css/postcss/project/film-page.css

Plugins list:

https://github.com/tsergeytovarov/vkino-dev/blob/master/Gruntfile.js#L23

Error:

https://monosnap.com/file/oGHI4pjATaXG6xmCfjcocY3yBDftUY

Deleting 82-84 and 89-106 lines in CSS input fix a error.

**Comment by ben-eb** [comment]
This module already knows how to handle empty rules (https://github.com/ben-eb/postcss-merge-rules/commit/7ce3da99ede2a66187c90857afc7a44d1b7951e3). Are you sure it is not a hole in the AST?

**Comment by ai** [comment]
I thought that postcss-nested may broke AST, but I can’t find how.

**Comment by ai** [comment]
https://github.com/postcss/postcss/blob/master/lib/rule.js#L7

**Comment by demiazz** [comment]
I have similar error on my build config. 

This function called for release build. This step do only simple things: minify, replace urls, and split to files. Clean precompiled CSS on input. 
```javascript
gulp.task(releaseTaskName, [ 'images:release', bundleTaskName ], function () {
  return tools.release(name);
});

function release (name) {
  let files = path.join(options.tmpBundlesRoot, `${ name }.css`);

  return gulp.src(files)
    .pipe(error.plumber())
    .pipe(postcss([
      postcssUrl({ url: replaceUrl(true) }),
      nano()
    ]))
    .pipe(utils.manifest())
    .pipe(utils.dest())
    .pipe(rename(`${ name }-ie.css`))
    .pipe(bless())
    .pipe(utils.manifest())
    .pipe(utils.dest());
};
```

I have several release tasks, for different files. Following exception throwed when one of files processed:

```
TypeError: Cannot read property 'map' of undefined
  at getDeclarations (/home/demiazz/ebay-social/front/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:55:22)
  at partialMerge (/home/demiazz/ebay-social/front/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:77:67)
  at /home/demiazz/ebay-social/front/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:155:17
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/container.js:143:30
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/container.js:104:26
  at Root.each (/home/demiazz/ebay-social/front/node_modules/postcss/lib/container.js:91:22)
  at Root.eachInside (/home/demiazz/ebay-social/front/node_modules/postcss/lib/container.js:103:21)
  at Root.eachRule (/home/demiazz/ebay-social/front/node_modules/postcss/lib/container.js:141:21)
  at /home/demiazz/ebay-social/front/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:161:13
  at LazyResult.run (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:193:24)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:107:37
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at /home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:118:27
  at LazyResult.asyncTick (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:120:15)
  at processing.Promise.then._this2.processed (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:146:20)
  at LazyResult.async (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:144:27)
  at LazyResult.then (/home/demiazz/ebay-social/front/node_modules/postcss/lib/lazy-result.js:72:21)
  at Transform.stream._transform (/home/demiazz/ebay-social/front/node_modules/gulp-postcss/index.js:45:8)
  ...
```

postcss-nested doesn't used for errored file's processing.

**Comment by ben-eb** [comment]
@ai I am not sure if this is my issue or a PostCSS one. I can guard against stringifying a rule when it has no nodes, but I would like some reproducible test case for this. Do rules always have nodes? If they don't, how do I test that case? However as you linked there rule nodes should be an array, not undefined.

**Comment by ai** [comment]
@demiazz let’s debug :D

1. Can you remove `postcss-url` to be 100% that it is not broken AST?
2. Can you write here was last argument was sent ot `getDeclarations` function in `postcss-merge-rules/index.js` on 54 line.

**Comment by demiazz** [comment]
OK, I will try debug this case tomorrow.

**Comment by ai** [comment]
@ben-eb does `postcss-merge-rules` works with `@charset "UTF-8";`. It is `atrule` and has no `nodes` property at all. Maybe it is a problem?

**Comment by ben-eb** [comment]
@ai It seems so. https://github.com/ben-eb/postcss-merge-rules/commit/bbad0fb2e2bc303a57005fcf5c3e63f81f291c52
